namespace FakeCommunication.Api.Contracts;

/// <summary>
/// TR: FakeCommunication provider'ının kabul ettiği SMS/e-posta isteği için ürettiği provider referansı ve durum bilgisini temsil eder.
/// EN: Represents the provider reference and status returned by FakeCommunication for an accepted SMS/email request.
/// </summary>
public sealed class SendMessageResponse
{
    /// <summary>
    /// TR: Provider yanıtını oluşturur.
    /// EN: Creates the provider response.
    /// </summary>
    /// <param name="messageId">
    /// TR: Fake provider tarafından üretilen benzersiz mesaj kimliği.
    /// EN: Unique message identifier generated by the fake provider.
    /// </param>
    /// <param name="status">
    /// TR: Provider'ın mesajı kabul durumunu ifade eden metin.
    /// EN: Text describing whether the provider accepted the message.
    /// </param>
    /// <param name="acceptedAt">
    /// TR: Provider'ın mesajı kabul ettiği UTC zaman bilgisi.
    /// EN: UTC timestamp at which the provider accepted the message.
    /// </param>
    public SendMessageResponse(Guid messageId, string status, DateTimeOffset acceptedAt)
    {
        MessageId = messageId;
        Status = status;
        AcceptedAt = acceptedAt;
    }

    /// <summary>
    /// TR: Fake provider tarafından üretilen benzersiz mesaj kimliğini döndürür.
    /// EN: Gets the unique message identifier generated by the fake provider.
    /// </summary>
    public Guid MessageId { get; }

    /// <summary>
    /// TR: Mesajın provider tarafından kabul edilip edilmediğini ifade eden durumu döndürür.
    /// EN: Gets the status indicating whether the provider accepted the message.
    /// </summary>
    public string Status { get; }

    /// <summary>
    /// TR: Mesajın provider tarafından kabul edildiği UTC zamanını döndürür.
    /// EN: Gets the UTC time at which the provider accepted the message.
    /// </summary>
    public DateTimeOffset AcceptedAt { get; }
}
