using FinWallet.Application.Banking;
using FinWallet.Application.Inbox;
using FinWallet.Shared.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace FinWallet.Api.Controllers;

/// <summary>
/// TR: Gateway `InternalService` policy ve downstream service key arkasında FakeBank callback'larını durable Inbox üzerinden işler; public JWT customer endpoint'i değildir.
/// EN: Processes FakeBank callbacks through durable Inbox behind the Gateway `InternalService` policy and downstream service key; this is not a public JWT customer endpoint.
/// </summary>
[ApiController]
[Route("api/v1/internal/bank/callbacks")]
public sealed class InternalBankCallbacksController : ControllerBase
{
    private readonly ProcessBankCallbackHandler _handler;

    /// <summary>TR: Durable callback handler bağımlılığıyla controller'ı oluşturur. EN: Creates controller with durable callback-handler dependency.</summary>
    /// <param name="handler">TR: Inbox + bank movement callback orchestrator'ı. EN: Inbox + bank-movement callback orchestrator.</param>
    public InternalBankCallbacksController(ProcessBankCallbackHandler handler)
    {
        _handler = handler ?? throw new ArgumentNullException(nameof(handler));
    }

    /// <summary>TR: Provider callback'ını Source+MessageId ile dedupe eder; aynı callback yüzlerce kez gelse de terminal finansal state replay-safe kalır. EN: Deduplicates provider callback by Source+MessageId; terminal financial state remains replay-safe even if the callback arrives hundreds of times.</summary>
    /// <param name="request">TR: Provider message/transaction/status bilgisi. EN: Provider message/transaction/status data.</param>
    /// <param name="cancellationToken">TR: MSSQL iptal sinyali. EN: MSSQL cancellation signal.</param>
    /// <returns>TR: Internal transaction state ve duplicate bilgisini döndürür. EN: Returns internal transaction state and duplicate state.</returns>
    [HttpPost]
    [ProducesResponseType(typeof(ServiceResult<BankCallbackResponse>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ServiceResult<object>), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ServiceResult<object>), StatusCodes.Status404NotFound)]
    [ProducesResponseType(typeof(ServiceResult<object>), StatusCodes.Status409Conflict)]
    public async Task<ActionResult<ServiceResult<BankCallbackResponse>>> ReceiveAsync([FromBody] BankCallbackRequest request, CancellationToken cancellationToken)
    {
        if (!Enum.TryParse<ExternalBankTransactionStatus>(request.Status, true, out var status))
        {
            return BadRequest(ServiceResult<BankCallbackResponse>.Failure("INVALID_BANK_CALLBACK", "The callback status is invalid."));
        }

        var result = await _handler.HandleAsync(request.MessageId, request.ExternalTransactionId, status, cancellationToken);
        return Ok(ServiceResult<BankCallbackResponse>.Success(
            new BankCallbackResponse(result.TransactionId, result.State.ToString(), result.WasDuplicate),
            result.WasDuplicate ? "BANK_CALLBACK_DUPLICATE" : "BANK_CALLBACK_PROCESSED",
            result.WasDuplicate ? "The callback had already been processed." : "The callback was processed successfully."));
    }
}

/// <summary>TR: Internal FakeBank callback request sözleşmesidir. EN: Internal FakeBank callback request contract.</summary>
public sealed class BankCallbackRequest
{
    /// <summary>TR: Provider tarafından stabil üretilen callback message kimliğini döndürür veya ayarlar. EN: Gets or sets stable callback-message identifier generated by the provider.</summary>
    public string MessageId { get; init; } = string.Empty;
    /// <summary>TR: FakeBank transaction kimliğini döndürür veya ayarlar. EN: Gets or sets FakeBank transaction identifier.</summary>
    public Guid ExternalTransactionId { get; init; }
    /// <summary>TR: `Pending`, `Completed` veya `Failed` provider durumunu döndürür veya ayarlar. EN: Gets or sets provider state `Pending`, `Completed` or `Failed`.</summary>
    public string Status { get; init; } = string.Empty;
}

/// <summary>TR: Internal bank callback processing response sözleşmesidir. EN: Internal bank-callback processing response contract.</summary>
public sealed class BankCallbackResponse
{
    /// <summary>TR: Callback response oluşturur. EN: Creates callback response.</summary>
    /// <param name="transactionId">TR: Internal FinancialTransaction kimliği. EN: Internal FinancialTransaction identifier.</param>
    /// <param name="state">TR: Güncel bank movement state'i. EN: Current bank-movement state.</param>
    /// <param name="wasDuplicate">TR: Duplicate callback bilgisidir. EN: Duplicate-callback state.</param>
    public BankCallbackResponse(Guid transactionId, string state, bool wasDuplicate)
    {
        TransactionId = transactionId;
        State = state;
        WasDuplicate = wasDuplicate;
    }

    /// <summary>TR: Internal transaction kimliğini döndürür. EN: Gets internal transaction identifier.</summary>
    public Guid TransactionId { get; }
    /// <summary>TR: Güncel bank movement state'ini döndürür. EN: Gets current bank-movement state.</summary>
    public string State { get; }
    /// <summary>TR: Callback duplicate bilgisini döndürür. EN: Gets duplicate-callback state.</summary>
    public bool WasDuplicate { get; }
}
