namespace FakeCutoff.Api.Contracts;

/// <summary>
/// TR: FakeCutoff sağlayıcısının işlem zamanı için verdiği anlık işlenebilirlik, processing günü ve settlement günü kararını temsil eder.
/// EN: Represents the FakeCutoff provider decision containing immediate processability, processing date and settlement date for an operation timestamp.
/// </summary>
public sealed class CutoffEvaluationResponse
{
    /// <summary>
    /// TR: Cutoff değerlendirme yanıtını oluşturur.
    /// EN: Creates the cutoff-evaluation response.
    /// </summary>
    /// <param name="referenceId">
    /// TR: Fake provider'ın değerlendirme için ürettiği benzersiz dış referans.
    /// EN: Unique external reference generated by the fake provider for the evaluation.
    /// </param>
    /// <param name="canProcessNow">
    /// TR: İsteğin mevcut business day/cutoff kuralları altında aynı processing gününde işlenip işlenemeyeceğini belirtir.
    /// EN: Indicates whether the request can be processed on the same processing date under current business-day/cutoff rules.
    /// </param>
    /// <param name="processingDate">
    /// TR: İşlemin provider tarafından işleme alınacağı yerel business tarihi.
    /// EN: Local business date on which the provider will process the operation.
    /// </param>
    /// <param name="settlementDate">
    /// TR: İşlemin tamamlanmasının beklendiği yerel business settlement tarihi.
    /// EN: Local business settlement date on which the operation is expected to settle.
    /// </param>
    /// <param name="cutoffTime">
    /// TR: Seçilen kuralın yerel cutoff saatini gösterir.
    /// EN: Local cutoff time of the selected rule.
    /// </param>
    /// <param name="timeZoneId">
    /// TR: Hesaplamada kullanılan provider timezone kimliği.
    /// EN: Provider timezone identifier used for the calculation.
    /// </param>
    /// <param name="reason">
    /// TR: Processing kararının business day/cutoff gerekçesini açıklayan makine-okunabilir nedeni.
    /// EN: Machine-readable reason describing the business-day/cutoff basis of the processing decision.
    /// </param>
    public CutoffEvaluationResponse(
        Guid referenceId,
        bool canProcessNow,
        DateOnly processingDate,
        DateOnly settlementDate,
        TimeOnly cutoffTime,
        string timeZoneId,
        string reason)
    {
        ReferenceId = referenceId;
        CanProcessNow = canProcessNow;
        ProcessingDate = processingDate;
        SettlementDate = settlementDate;
        CutoffTime = cutoffTime;
        TimeZoneId = timeZoneId;
        Reason = reason;
    }

    /// <summary>
    /// TR: Fake provider değerlendirmesinin benzersiz dış referansını döndürür.
    /// EN: Gets the unique external reference of the fake-provider evaluation.
    /// </summary>
    public Guid ReferenceId { get; }

    /// <summary>
    /// TR: İşlemin aynı processing gününde işlenip işlenemeyeceğini döndürür.
    /// EN: Gets whether the operation can be processed on the same processing date.
    /// </summary>
    public bool CanProcessNow { get; }

    /// <summary>
    /// TR: Provider'ın belirlediği yerel processing business tarihini döndürür.
    /// EN: Gets the local processing business date selected by the provider.
    /// </summary>
    public DateOnly ProcessingDate { get; }

    /// <summary>
    /// TR: Provider'ın belirlediği yerel settlement business tarihini döndürür.
    /// EN: Gets the local settlement business date selected by the provider.
    /// </summary>
    public DateOnly SettlementDate { get; }

    /// <summary>
    /// TR: Seçilen cutoff kuralının yerel saatini döndürür.
    /// EN: Gets the local time of the selected cutoff rule.
    /// </summary>
    public TimeOnly CutoffTime { get; }

    /// <summary>
    /// TR: Cutoff hesaplamasında kullanılan timezone kimliğini döndürür.
    /// EN: Gets the timezone identifier used by the cutoff calculation.
    /// </summary>
    public string TimeZoneId { get; }

    /// <summary>
    /// TR: Provider kararının makine-okunabilir gerekçesini döndürür.
    /// EN: Gets the machine-readable reason for the provider decision.
    /// </summary>
    public string Reason { get; }
}
