namespace FakeBank.Api.Models;

/// <summary>
/// TR: FakeBank simulatorının kendi sınırları içinde tuttuğu currency bazlı harici banka hesabını temsil eder; FinWallet internal wallet/ledger state'i değildir.
/// EN: Represents a currency-specific external bank account owned by the FakeBank simulator; it is not FinWallet internal wallet/ledger state.
/// </summary>
public sealed class FakeBankAccount
{
    /// <summary>
    /// TR: Yeni harici banka hesabı kaydını oluşturur.
    /// EN: Creates a new external bank-account record.
    /// </summary>
    /// <param name="accountId">TR: Provider tarafından üretilen benzersiz hesap kimliği. EN: Unique account identifier generated by the provider.</param>
    /// <param name="externalCustomerReference">TR: FinWallet müşterisini provider tarafında temsil eden dış referans. EN: External reference representing the FinWallet customer at the provider.</param>
    /// <param name="currency">TR: Hesabın para birimi. EN: Currency of the account.</param>
    /// <param name="iban">TR: Simulator tarafından üretilen IBAN-benzeri hesap numarası. EN: IBAN-like account number generated by the simulator.</param>
    /// <param name="status">TR: Hesabın başlangıç provider durumu. EN: Initial provider state of the account.</param>
    /// <param name="createdAt">TR: Hesabın oluşturulduğu UTC zaman. EN: UTC time at which the account was created.</param>
    public FakeBankAccount(Guid accountId, Guid externalCustomerReference, string currency, string iban, FakeBankAccountStatus status, DateTimeOffset createdAt)
    {
        if (accountId == Guid.Empty) throw new ArgumentException("Account identifier cannot be empty.", nameof(accountId));
        if (externalCustomerReference == Guid.Empty) throw new ArgumentException("External customer reference cannot be empty.", nameof(externalCustomerReference));
        ArgumentException.ThrowIfNullOrWhiteSpace(currency);
        ArgumentException.ThrowIfNullOrWhiteSpace(iban);

        AccountId = accountId;
        ExternalCustomerReference = externalCustomerReference;
        Currency = currency.Trim().ToUpperInvariant();
        Iban = iban.Trim().ToUpperInvariant();
        Status = status;
        CreatedAt = createdAt;
    }

    /// <summary>TR: Provider hesap kimliğini döndürür. EN: Gets the provider account identifier.</summary>
    public Guid AccountId { get; }

    /// <summary>TR: Provider tarafındaki müşteri referansını döndürür. EN: Gets the provider-side customer reference.</summary>
    public Guid ExternalCustomerReference { get; }

    /// <summary>TR: Hesabın currency kodunu döndürür. EN: Gets the account currency code.</summary>
    public string Currency { get; }

    /// <summary>TR: Simulator IBAN-benzeri hesap numarasını döndürür. EN: Gets the simulator IBAN-like account number.</summary>
    public string Iban { get; }

    /// <summary>TR: Hesabın provider yaşam döngüsü durumunu döndürür. EN: Gets the provider lifecycle state of the account.</summary>
    public FakeBankAccountStatus Status { get; private set; }

    /// <summary>TR: Provider tarafındaki mevcut hesap bakiyesini döndürür. EN: Gets the current account balance at the provider.</summary>
    public decimal Balance { get; private set; }

    /// <summary>TR: Hesabın oluşturulduğu UTC zamanı döndürür. EN: Gets the UTC account creation time.</summary>
    public DateTimeOffset CreatedAt { get; }

    /// <summary>
    /// TR: Pending hesap açılışını aktif duruma geçirir.
    /// EN: Transitions a pending account opening into Active state.
    /// </summary>
    public void Activate()
    {
        if (Status != FakeBankAccountStatus.Pending) throw new InvalidOperationException("Only pending accounts can be activated.");
        Status = FakeBankAccountStatus.Active;
    }

    /// <summary>
    /// TR: Harici hesaba belirtilen currency ile para girişi uygular.
    /// EN: Credits the external account using the specified currency.
    /// </summary>
    /// <param name="amount">TR: Pozitif kredi tutarı. EN: Positive credit amount.</param>
    /// <param name="currency">TR: İşlem currency kodu. EN: Transaction currency code.</param>
    public void Credit(decimal amount, string currency)
    {
        EnsureActiveAndCurrency(amount, currency);
        Balance += amount;
    }

    /// <summary>
    /// TR: Harici hesaptan belirtilen currency ile para çıkışı uygular ve provider bakiyesinin negatife düşmesini engeller.
    /// EN: Debits the external account using the specified currency and prevents the provider balance from becoming negative.
    /// </summary>
    /// <param name="amount">TR: Pozitif debit tutarı. EN: Positive debit amount.</param>
    /// <param name="currency">TR: İşlem currency kodu. EN: Transaction currency code.</param>
    public void Debit(decimal amount, string currency)
    {
        EnsureActiveAndCurrency(amount, currency);
        if (Balance < amount) throw new InvalidOperationException("External bank account has insufficient balance.");
        Balance -= amount;
    }

    /// <summary>
    /// TR: Para hareketi öncesinde hesap aktifliği, pozitif tutar ve currency eşleşmesini doğrular.
    /// EN: Validates account activity, positive amount and currency match before a money movement.
    /// </summary>
    /// <param name="amount">TR: Doğrulanacak işlem tutarı. EN: Transaction amount to validate.</param>
    /// <param name="currency">TR: Doğrulanacak işlem currency kodu. EN: Transaction currency code to validate.</param>
    private void EnsureActiveAndCurrency(decimal amount, string currency)
    {
        if (Status != FakeBankAccountStatus.Active) throw new InvalidOperationException("External bank account is not active.");
        if (amount <= 0) throw new ArgumentOutOfRangeException(nameof(amount));
        ArgumentException.ThrowIfNullOrWhiteSpace(currency);
        if (!string.Equals(Currency, currency.Trim(), StringComparison.OrdinalIgnoreCase)) throw new InvalidOperationException("External account currency does not match transaction currency.");
    }
}
