using FinWallet.Domain.Shared;

namespace FinWallet.Application.Banking;

/// <summary>
/// TR: Dış banka hesap açılışı veya durum sorgusundan dönen provider hesabını provider DTO'sundan bağımsız olarak taşır.
/// EN: Carries an external-bank account returned by account opening or status lookup independently from provider DTOs.
/// </summary>
public sealed class ExternalBankAccountResult
{
    /// <summary>
    /// TR: Dış banka hesap sonucunu oluşturur.
    /// EN: Creates an external-bank account result.
    /// </summary>
    /// <param name="accountId">TR: Provider tarafından üretilen hesap kimliği. EN: Account identifier generated by the provider.</param>
    /// <param name="iban">TR: Provider tarafından dönen IBAN-benzeri hesap değeri. EN: IBAN-like account value returned by the provider.</param>
    /// <param name="currency">TR: Harici hesabın currency değeri. EN: Currency of the external account.</param>
    /// <param name="status">TR: Provider bağımsız hesap durumu. EN: Provider-independent account state.</param>
    public ExternalBankAccountResult(Guid accountId, string iban, CurrencyCode currency, ExternalBankAccountStatus status)
    {
        if (accountId == Guid.Empty) throw new ArgumentException("External account identifier cannot be empty.", nameof(accountId));
        ArgumentException.ThrowIfNullOrWhiteSpace(iban);
        AccountId = accountId;
        Iban = iban.Trim();
        Currency = currency;
        Status = status;
    }

    /// <summary>TR: Provider hesap kimliğini döndürür. EN: Gets the provider account identifier.</summary>
    public Guid AccountId { get; }

    /// <summary>TR: Provider IBAN-benzeri hesap değerini döndürür. EN: Gets the provider IBAN-like account value.</summary>
    public string Iban { get; }

    /// <summary>TR: Harici hesap currency değerini döndürür. EN: Gets the external-account currency.</summary>
    public CurrencyCode Currency { get; }

    /// <summary>TR: Provider bağımsız hesap durumunu döndürür. EN: Gets the provider-independent account state.</summary>
    public ExternalBankAccountStatus Status { get; }
}
